version: '3.4'
services:

  incident:
    image: incident
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "8080:8080"
    command: mvn spring-boot:run